### PR TITLE
marcogallardo/sc-5847/add-preflight-rules-for-pdf-x-1a-and-pdf

### PR DESCRIPTION
**Pull request by marco-gallardo**
Ticket:
[Add Preflight Rules for PDF/X-1a and PDF/X-4](https://app.shortcut.com/share-local-media/story/5847/add-preflight-rules-for-pdf-x-1a-and-pdf-x-4)

Description of changes:
1. Create new `MatchInfoPdfxVersions` rule. It accepts a set of PDF specifications which are used to validate a given pdf file by comparing them against its _info_ metadata AND validate  _PDFX-1a_ max version is 1.3 and _PDFX-4_ max version is 1.6.
2. Update _PDFX-1a_ profile with new `MatchInfoPdfxVersions` so profile accepts _PDFX-1a_ and _PDFX-4_ versions.
3. If given pdf file is compliant with at least with 1 listed PDFX format then don't return _messages_ -to prevent issues on flight-attendant- otherwise return the specific issue on the description within _messages_.

### CODE REVIEW

**Review by stjohncj — CHANGES_REQUESTED** [review]
Rather than modifying the existing PDFX-1a profile to accept both PDFX-1a and PDFX-4, I think there needs to be a new profile created for PDFX that does this.  We shouldn't be adjusting this profile within the pdf-preflight gem.  Any additions here should be able to be resubmitted back downstream from our fork to the yob mainline.

**Comment by stjohncj** [comment]
Curious, why does this implement a new rule class MatchInfoPdfxVersions rather than use the existing MatchInfoEntries (https://github.com/share-local-media/pdf-preflight/blob/slm/lib/preflight/rules/match_info_entries.rb) @marco-gallardo ?

**Comment by marco-gallardo** [comment]
> Curious, why does this implement a new rule class MatchInfoPdfxVersions rather than use the existing MatchInfoEntries (https://github.com/share-local-media/pdf-preflight/blob/slm/lib/preflight/rules/match_info_entries.rb) @marco-gallardo ?

Because there's no way to use `MatchInfoEntries` rule to do both validations at once.
```
rule MatchInfoEntries, <args for pdfx_1a> # this will fail when file is _pdfx_4_
rule MatchInfoEntries, <args for pdfx_4> # this will fail when file is _pdfx_1a_
```

**Comment by marco-gallardo** [comment]
> Rather than modifying the existing PDFX-1a profile to accept both PDFX-1a and PDFX-4, I think there needs to be a new profile created for PDFX that does this. We shouldn't be adjusting this profile within the pdf-preflight gem. Any additions here should be able to be resubmitted back downstream from our fork to the yob mainline.

@stjohncj I created a new `BasePDFX` profile, can you review new changes please?

**Review by stjohncj — APPROVED** [review]

**Pull request merged**
